name: 'Issue Optomo license'
description: 'Issue a Optomo license that can be sent to clients'
inputs:
  licensee:
    description: 'Licensee'
    required: true
  maxAutomations:
    description: 'Max automations'
    required: true
  maxBluePrismLicense:
    description: 'Max Blue Prism licenses'
    required: true
  starts:
    description: 'Starts [2021-12-31T12:00:00Z]'
    default: '2021-12-31T12:00:00Z'
    required: true
  expires:
    description: 'Expires [2023-12-31T12:00:00Z]'
    default: '2023-12-31T12:00:00Z'
    required: true
outputs:
  licensekey:
    description: 'licensekey'

runs:
  using: 'node16'
  main: '../../hack/dist/index.js'
