name: Issue Optomo license

on:
  workflow_dispatch:
    inputs:
      licensee:
        description: 'Licensee'
        required: true
      maxAutomations:
        description: 'Max automations'
        required: true
      maxBluePrismLicense:
        description: 'Max Blue Prism licenses'
        required: true
      starts:
        description: 'Starts [2022-12-31T12:00:00Z]'
        default: '2022-12-31T12:00:00Z'
        required: true
      expires:
        description: 'Expires [2023-12-31T12:00:00Z]'
        default: '2023-12-31T12:00:00Z'
        required: true

jobs:
  issue-license:
    environment: LICENSE_SECRETS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run issue license script
        id: license_script
        uses: ./.github/actions
        env:
          LICENSE_PRIVATE_KEY: ${{ secrets.LICENSE_PRIVATE_KEY }}
          LICENSE_PUBLIC_KEY: ${{ secrets.LICENSE_PUBLIC_KEY }}
        with:
          name: ${{ github.event.inputs.name }}
      - name: echo file
        run: echo ${{ steps.license_script.outputs.licensekey }} > license.lic
      - name: Upload license
        uses: actions/upload-artifact@v3
        with:
          name: license file
          path: license.lic
